### PR TITLE
FEATURE- Easier Instruction Creation

### PR DESCRIPTION
**Pull request by YouYue123**
The feature can make instruction creation easier from code. 

There is one  EasyInstruction class inside which provide an easier way to create instruction instead using bunch of switch-case. And it can help developer create a simple instruction very quickly and intuitively.

I will be very happy if this feature can help you. ^_^

### CODE REVIEW

**Comment by ephread** [comment]
Thanks for this pull request @YouYue123! I'll take a look later this week. :)

**Comment by ephread** [comment]
@YouYue123: I'm conflicted about this. I don't really believe _seeding_ Instructions, through dozens of calls, really provides an advantage over the common protocol-based approach, while retaining its flexibility. What are your thoughts on this?

**Comment by YouYue123** [comment]
Yes.

On flexibility side, you are totally right. 

But how about considering to provide a easier way to showcase at a glance? I think my way can help to achieve this kind of use case. Thanks ^_^

**Comment by ephread** [comment]
The code has changed a lot, I'm closing this pull request.

I really don't believe in the benefits of the approach, sadly. That said, however, I'm thinking of implementing a block-based approach, which would probably be the sweet spot between the two worlds

**Pull request closed without merging**
