### PR TITLE
Fix status bar above instructionsTopView

### PR DESCRIPTION
**Pull request by samwize**
This will create a snapshot of the status bar, add it to below `instructionsTopView`, and make window level higher than status bar level.

The window will obscure the real status bar.

### CODE REVIEW

**Comment by ephread** [comment]
@samwise: I like the idea, but it causes some flickering, did you notice this?

**Comment by samwize** [comment]
@ephread Yes I notice a flicker. Got to figure out.

**Comment by samwize** [comment]
I think the flicker is because of overlay.alpha = 0. So the status bar got animated in together with the rest.

Any good place/view to add the fakeStatusBar to that is behind the overlay?

**Comment by ephread** [comment]
Closing, because it's too old.

I'm working on a new method of displaying the overlay, using a extra window, this will probably enable the feature out of the box theough the use of window levels.

**Pull request closed without merging**
