### PR TITLE
Swift 4.2

### PR DESCRIPTION
**Pull request by Legoless**
### Checklist for this pull request

- [x] I have read the [guidelines for contributing](../CONTRIBUTING.md).
- [x] I have updated README.md, describing the new feature I'm adding (if applicable).
- [x] I have checked that my code additions did fail neither code linting checks nor unit/UI test.

### Description

Support for Swift 4.2, nothing else.

### CODE REVIEW

**Comment by edwardmp** [comment]
@ephread CI fails on a pre-test step. Can you check this out and merge this in? Thanks.

**Comment by ephread** [comment]
Thanks for the work @Legoless, but Swift 4.2 support has been available for some time in the `swift4` branch. Sorry I didn't mention this in the README.

**Comment by Legoless** [comment]
All right cool, no problem. Close the PR, if you like, I am keeping my fork on until everything is on master, thanks!

**Comment by canaksoy** [comment]
merge to master please @ephread

**Comment by ephread** [comment]
1.2.2 has been released a few days ago, with support for swift 4.2.

**Pull request closed without merging**
